### ISSUE TITLE
private instead of public in uarray

### ISSUE THREAD

**Issue by mulderm** [msharov/ustl#10]
Hi,

Should line 80 in uarray.h (in master) not be private instead of public?

**Comment by msharov** [comment]
No, it should not. Having the array member public is what allows aggregate initialization and assignment: a={1,2,3,4}, which is part of the required std::array functionality.

**Comment by mulderm** [comment]
Hi Mike,

Ah ok, I did not know that was part of the requirements of the STL array. I hardly use STL.
Thanks for the explanation.

Regards, Marcel

On 02 Jun 2015, at 19:00, Mike Sharov <notifications@github.com<mailto:notifications@github.com>> wrote:


No, it should not. Having the array member public is what allows aggregate initialization and assignment: a={1,2,3,4}, which is part of the required std::array functionality.
