### ISSUE TITLE
Cross-compiling not working

### ISSUE THREAD

**Issue by AaronDMarasco-VSI** [msharov/ustl#11]
I am trying to cross-compile uSTL for a Xilinx Zynq development board (ARM processor). The `./configure` script claims to be able to cross-compile, but I don't see any of the hooks actually in there.

The command `./configure --with-demangler --force-inline --with-libstdc++ --without-mmx --host=arm-xilinx-linux-gnueabi` still builds for the host and never tried to run `arm-xilinx-linux-gnueabi-gcc`, etc.

It looks like the configure script builds and executes a `config.cpu` program, which is something that wouldn't work if cross-compiling. The cross-compile library does offer `sys/config/h`, etc, to parse for capabilities.

**Comment by AaronDMarasco-VSI** [comment]
#12 is my attempt.

**Comment by msharov** [comment]
The main branch of uSTL explicitly and vehemently does not support embedded platforms of any kind. Cross-compiling is only needed for embedded platforms, so I have no interest in implementing it.

**Comment by AaronDMarasco-VSI** [comment]
You might want to cherry-pick 3797a54863533997ebc533430d3592e0e13e9ee0 then. The `configure` script implied it was possible. That change removes the options from the `--help` display. I don't know how to send a pull request for that one changeset.

There are a few others that might interest you: d000afe7767a75ebfb90a7deaab1ce9d6241f558 and 28fd0fd3332dd0760fae442c89a165dc6a695654.

**Comment by msharov** [comment]
3797a54 is reasonable. Merged in commit fa170b13d19ea7b7ab580dc5fd729720d23e5613.

d000afe is rejected. Tests should always be run with make check, not individually, because any library change can impact multiple tests.

28fd0fd is also rejected. The UNIX philosophy is to produce no output when everything is fine.
