### ISSUE TITLE
Possible bug in "uoff_t FirstBit (uint64_t v, uoff_t nbv)" (uutility.h)

### ISSUE THREAD

**Issue by AaronDMarasco-VSI** [msharov/ustl#13]
`gcc` notes that [__builtin_clzll](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) should be used for `uint64_t (unsigned long long)`. Right now the code uses `__builtin_clzl` (with one `l`).

**Comment by msharov** [comment]
Fixed by commit 0d4c8ddc608b5b2c3495ed6de89dcafded420e33
