### ISSUE TITLE
Linking on Fedora 22

### ISSUE THREAD

**Issue by Gerii** [msharov/ustl#15]
After figuring out that Debian based distributions aren't supported out of the box without some workarounds I installed Fedora 22 in a VM. I installed the ustl as advised in the documentation. (In the end I would like to use a different prefix, however at first I just wanted to get it working.)
With this setup compiling the hello world example from the doc works fine, however I can't get it to link properly.

[gery@localhost ~]$ gcc -lustl main.cpp
/usr/local/lib/libustl.so: undefined reference to `__cxa_end_catch'
/usr/local/lib/libustl.so: undefined reference to `__cxa_allocate_exception'
/usr/local/lib/libustl.so: undefined reference to `typeinfo for unsigned char'
/usr/local/lib/libustl.so: undefined reference to `typeinfo for long'
/usr/local/lib/libustl.so: undefined reference to `typeinfo for unsigned int'
/usr/local/lib/libustl.so: undefined reference to `typeinfo for char const*'
/usr/local/lib/libustl.so: undefined reference to `__gxx_personality_v0'
/usr/local/lib/libustl.so: undefined reference to `__cxa_begin_catch'
/usr/local/lib/libustl.so: undefined reference to `__cxa_throw'
/usr/local/lib/libustl.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/local/lib/libustl.so: undefined reference to `typeinfo for unsigned long'
/usr/local/lib/libustl.so: undefined reference to `typeinfo for char'
/usr/local/lib/libustl.so: undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/local/lib/libustl.so: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info'
collect2: Fehler: ld gab 1 als Ende-Status zurück

**Comment by msharov** [comment]
Please look in the generated Config.mk. It should contain (line 48):
STAL_LIBS   := -lsupc++
If it does not, find the location of libsupc++.a. If your libsupc++.a is not in /usr/lib, you will have to rerun configure and specify the prefix containing it (--prefix=/usr/lib/x86_64-unknown-gnu) or just the libdir (--libdir=/usr/lib/x86_64-unknown-gnu/lib).

These problems are caused by distributions not following the Linux Filesystem Standard, which requires platform libraries to be installed in /usr/lib. Feel free to complain to distribution owners, but action is unlikely.

**Comment by msharov** [comment]
Commit baca98ee74391b52af24ce79976603d5bf9cee14 helps detect this problem and fail compilation with an informative message.

**Comment by Gerii** [comment]
I now got it working on Fedora - I was missing the libstdc++-static package.
However I also need to get it working on Ubuntu unfortunately. Copying the created files from Fedora just leads to linker errors so I tried your tip setting the libdir or the prefix to /usr/lib/gcc/x86_64-linux-gnu/4.9/ where my libsupc++.a is located.
Unfortunately I always get the following error message:
utypes.h:12:6: error: #error "This library compiles only on UNIX systems."
I also tried to set the includedir to /usr/include/x86_64-linux-gnu and the libdir to /usr/lib/x86_64-linux-gnu/ as you said in this bug report https://github.com/msharov/ustl/issues/3 which allows me to install the ustl but I get the same error as above when trying to compile a program using the ustl.

**Comment by Gerii** [comment]
Update: Seems I was just using the wrong order when calling Ubuntus version of gcc.
gcc -lustl main.cpp < doesn't work on Ubuntu
gcc main.cpp -lustl < works

**Comment by msharov** [comment]
-prefix should be set to /usr; that is the containing directory of the standard hierarchy of bin, lib, share, etc. -libdir should be set to /usr/lib/x86_64-linux-gnu on your system. And as for the /4.9, that just makes me angry. It seems that there is simply no way of finding libraries except for the damned brute force search of the entire filesystem. I simply can not imagine the depth of incompetence (or malice) it took to create such a system.

Anyway, you can add an additional lib search directory with -customlibdir=/usr/lib/gcc/x86_64-linux-gnu/4.9 option to configure. Or just give up and edit Config.mk manually. Or switch to a sane distribution, like Arch.

**Comment by dfateyev** [comment]
FYI, ustl has been recently updated to version 2.3 in Fedora (22+) and RHEL 6, 7 (EPEL).
Currently in testing, the packages will normally reach official repos within 1 week (Fedora) or 2 weeks (EPEL) if there are no complains.
