### ISSUE TITLE
error :(

### ISSUE THREAD

**Issue by b4zz4** [msharov/ustl#16]
**make**

>    Compiling bktrace.cc ...
> In file included from ulimits.h:7:0,
>                 from bktrace.h:7,
>                 from bktrace.cc:6:
> utypes.h:12:6: error: #error "This library requires standard UNIX headers to compile."
>     #error "This library requires standard UNIX headers to compile."
>      ^
> make: *** [.o/bktrace.o] Error 1

**Comment by msharov** [comment]
This error indicates that the configure script could not find one of the required headers fcntl.h, sys/stat.h, or unistd.h. All UNIX systems, such as Linux, BSD, SunOS, or Solaris, have these headers installed in /usr/include. Please verify that they are there and that you did not tell configure to look elsewhere by specifying --prefix, --includedir, and --oldincludedir as somewhere else. If you are not compiling on a UNIX system, such as Windows, please read the uSTL web page, where Windows is explicitly listed as not supported, for this and many other reasons.

**Comment by msharov** [comment]
Closing due to submitter's lack of interest.
