### ISSUE TITLE
string (const_pointer s) constructor has undesired behavior

### ISSUE THREAD

**Issue by bitladen** [msharov/ustl#17]
the const_pointer constructor catches pointer type as well, therefore you may get undesired behavior when assigning from non-const char*

easy fix: ustring.cc
string::string (const_pointer s) noexcept: memblock ()
{
//    if (!s) s = "";
//    relink (s, strlen(s));  // WRONG
	assign (s, strlen (s));  // correct!
}

example code:
int main(void)
{
	char buf[]="my test string";
	string test_string(buf);

	cout << '"' << test_string << '"' << endl;
	memset(buf,0,sizeof(buf));
	cout << '"' << test_string << '"' << endl; // WHOOPS
}

output:
"my test string"
"              "  (it's actually \0\0\0\0\0\0\0 not spaces here) LOL

**Comment by msharov** [comment]
String was intentionally implemented this way from the beginning, and this is explicitly mentioned on the web page; see index.html#Strings.
