### ISSUE TITLE
class ifstream can leak file descriptor

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#18]
Hello !
I'm looking at class ifstream definition and I can't see a destructor that takes care of closing the underlying file descriptor if it goes out of scope.

Cheers !

**Comment by msharov** [comment]
ifstream stores the file descriptor in an fstream object _file. The descriptor is closed in fstream's destructor. See fstream.cc:50

**Comment by mingodad** [comment]
Thanks !
I was going to delete the issue after realizing it when following the code.
Cheers !
