### ISSUE TITLE
istringstream::getline bug ?

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#19]
Hello !
I'm trying to read a file line by line inside a loop and looking inside istringstream::getline there is a lot o processing that is not optimal to use inside a loop, also it doesn't seem to work properly see demo bellow:
```
#include <ustl.h>

int main()
{
    ustl::string fname = "test.csv";
    ustl::ifstream fd_in(fname, ustl::ios::in);
    //fd_in.set_delimiters("");
    ustl::fstream fd_out;
    //fd_in.open(fname, ustl::ios::in);
    fd_out.open(fname + "2", ustl::ios::out);

    ustl::string line;
    while( !fd_in.eof() )
    {
        fd_in.getline(line);
        fd_out.write(line, line.size());
        fd_out.write("\n", 1);
    }
    return 0;
}
```
Here is test.csv:
```
"id","name"
1,"joe"
2,"mary"

```
And here the program generated test.csv2 (expected the same as test.csv):
It dequote the ("id") and do not read the first line properly.
```
id
,"name"
1,"joe"
2,"mary"

```

Also if I declare ifstream without parameters the progam compiles fine but do not link:
main.cpp:(.text.startup+0x31)||undefined reference to `ustl::ifstream::ifstream()'|
```
    ustl::ifstream fd_in;
    fd_in.open(fname, ustl::ios::in);
```
Cheers !

**Comment by msharov** [comment]
Wow! A real bug report! Congratulations! You are the first to use uSTL streams since... well... ever, and have the privilege of discovering the first real bug ever reported against them :)

**Comment by mingodad** [comment]
Hello !
It reads the test.csv fine now but seems that ustl::getline should return null on eof, look at this sample:
```
#define USE_STD
#ifndef USE_STD
    #include <string>
    #include <iostream>
    #include <sstream>
    namespace ustl = std;
#else
    #include <ustl.h>
    namespace ustd = ustl;
#endif


int main()
{
    // read file line by line
    ustl::istringstream input;
    input.str("1\n2\n3\n4\n5\n6\n7\n");
    int sum = 0;
    for (ustl::string line; ustl::getline(input, line); ) {
        sum += ustl::stoi(line);
    }
    ustl::cout << "\nThe sum is: " << sum << "\n";
}
```
When using std the program show the sum but when using ustl it remains on the for loop forever.
Cheers !

**Comment by mingodad** [comment]
The example come from http://en.cppreference.com/w/cpp/string/basic_string/getline and altough it says that std::getline return the istream on linux and on os x this program works so somehow the documentation is not correct or the libraries sent with the compilers/os are not properly implemented.

**Comment by mingodad** [comment]
I even tried to catch exceptions but none:
```
#define USE_STD
#ifdef USE_STD
    #include <string>
    #include <iostream>
    #include <sstream>
    namespace ustd = std;
#else
    #include <ustl.h>
    namespace ustd = ustl;
#endif


int main()
{
    // read file line by line
    ustd::istringstream input;
    input.str("1\n2\n3\n4\n5\n6\n7\n");
    int sum = 0;
    try
    {
        for (ustd::string line; ustd::getline(input, line); ) {
            sum += ustd::stoi(line);
        }
    }
    catch(const ustd::exception& e)
    {
        ustd::cout << "Exception: " << e.what() << sum << "\n";
    }
    ustd::cout << "\nThe sum is: " << sum << "\n";
}
```

**Comment by msharov** [comment]
You are trying too hard :) istream includes operator bool, which is what gets invoked here, returning !(failbit|badbit). uSTL does not currently set those on eof.

**Comment by msharov** [comment]
Commit e89cd7cecbf8fc33cafe77e99762457ea5fa5ab0 fixes this problem and your example passes.
