### ISSUE TITLE
On debian/ubuntu configure fail

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#26]
Hello !
On debian/ubuntu the "configure" script can not detect existence of:
// Define to 1 if you have the <sys/stat.h> header file.
#undef HAVE_SYS_STAT_H

// Define to 1 if you have the <sys/types.h> header file.
#undef HAVE_SYS_TYPES_H

I need to manually set then.

**Comment by msharov** [comment]
So where are your sys/stat.h and sys/types.h? On a sane system they are in /usr/include/sys/stat.h and /usr/include/sys/types.h

**Comment by mingodad** [comment]
On my ubuntu 14.04 they are at: /usr/include/linux

**Comment by msharov** [comment]
Those are the kernel include files. I need the ones from libc.

**Comment by mingodad** [comment]
/usr/include$ find . -name stat.h
./asm-generic/stat.h
./linux/stat.h
./x86_64-linux-gnu/asm/stat.h
./x86_64-linux-gnu/bits/stat.h
./x86_64-linux-gnu/sys/stat.h

/usr/include$ find . -name types.h
./asm-generic/types.h
./pci/types.h
./cairomm-1.0/cairomm/types.h
./linux/types.h
./gwenhywfar4/gwenhywfar/types.h
./x86_64-linux-gnu/asm/types.h
./x86_64-linux-gnu/bits/types.h
./x86_64-linux-gnu/sys/types.h
./netlink/types.h
./c++/4.9/parallel/types.h
./rpc/types.h
./webp/types.h
./wx-3.0/wx/types.h
./wx-2.8/wx/types.h

**Comment by mingodad** [comment]
It seems that because we can have multilib 32/63 bits they are in $ARCH folder.

**Comment by msharov** [comment]
Yes, this is a recurring problem with Debian-based distros. This directory arrangement violates the linux filesystem hierarchy standard, but Debian does not really care. I submitted a request to change it, but I doubt it will happen in our lifetime. For now, I'm resigned to hardcoding the arch subdir in the search path.
