### ISSUE TITLE
ustl streams performance

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#27]
Hello !
Now that ustl have a minimal streams working I did a comparison with the c++ std on ubuntu 14.04, it reads a csv file of 915254KB and write it to another file line by line, ustl performance is around 8 times slower (800%) than std, memory usage ustl 900KB and std 1.5MB:
```
std -> time ./clean-nl-inquotes 
ted-contracts-2012.csv
Hello world! Alvarez

real	0m9.787s
user	0m1.829s
sys	0m2.443s
```
```
ustl -> time ./clean-nl-inquotes 
ted-contracts-2012.csv
Hello world! Alvarez

real	1m7.993s
user	0m57.783s
sys	0m5.515s
```
```
#define USE_STD2
#ifdef USE_STD
    #include <string>
    #include <iostream>
    #include <fstream>
    #include <sstream>
    #include <algorithm>
    namespace ustd = std;
#else
    #include <ustl.h>
    namespace ustd = ustl;
#endif

#include <dirent.h>
#include <errno.h>

bool startsWith(const ustd::string& s, const ustd::string& preffix)
{
    return s.size() >= preffix.size() && s.find(preffix) == 0;
}

bool endsWith(const ustd::string& s, const ustd::string& suffix)
{
    return s.size() >= suffix.size() && s.rfind(suffix) == (s.size()-suffix.size());
}

class OsDir
{
    DIR *m_dirp;
public:
    OsDir(){m_dirp = NULL;};
    ~OsDir(){close();}
    bool open(const char *root)
    {
        m_dirp = opendir(root);
        return m_dirp != NULL;
    }
    void close()
    {
        if(m_dirp)
        {
            closedir(m_dirp);
            m_dirp = NULL;
        }
    }
    struct dirent *readdir()
    {
        return m_dirp ? ::readdir(m_dirp) : NULL;
    };
};


int main()
{
    struct dirent *pde;
    OsDir dir;
    dir.open(".");

    while ((pde = dir.readdir())) {
            ustd::string fname = pde->d_name;
            if(endsWith(fname, ".csv"))
            {
                ustd::cout << fname << ustd::endl;
                //ustd::ifstream fd_in(fname, ustd::ios::in);
                ustd::ifstream fd_in;
                //fd_in.set_delimiters("");
                ustd::fstream fd_out;
                fd_in.open(fname, ustd::ios::in);
                fd_out.open(fname + "2", ustd::ios::out);

                size_t quote_count = 0;
                ustd::string line;
                while( ustd::getline(fd_in, line) )
                {
                    fd_out.write(line.c_str(), line.size());
                    quote_count += ustd::count(line.begin(), line.end(), '"');
                    //accumulate quote count to check when we have a valid line
                    if( (quote_count % 2) == 0 )
                    {
                        fd_out.write("\n", 1);
                        quote_count = 0;
                    }
                }
                break;
            }
    }

    ustd::string str;
    str += " Alvarez";

    ustd::cout << "Hello world!" << str << ustd::endl;
    return 0;
}
```

**Comment by msharov** [comment]
uSTL focuses on size, not performance. I am sure that if the code were profiled, some bottlenecks could be identified. If you want to try, go for it. Try increasing the stream buffer size from 256 bytes to 4k, for example, in ofstream.cc. However, many of those trade-offs will likely result in significantly increased code size and be unacceptable. The way I see it, if you want performance, you should not be using streams - write a real csv parser. Try lex. I have been using C++ for 25 years and I have never used a text stream for anything other than hello world. I recommend you do the same.

**Comment by mingodad** [comment]
Hello !

I did a profile on it and found that lot's of time were spent on
ustl::count searchin for '"' on a line, then I changed it for the classical
for loop then now big time is spent on:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ns/call  ns/call  name
 99.96      4.78     4.78                             main
  0.10      4.78     0.01   432232    11.59    11.59
 ustl::ios_base::fail() const
  0.10      4.79     0.01   432232    11.59    23.18
 ustl::ios_base::operator void*() const
  0.00      4.79     0.00   432250     0.00     0.00
 ustl::cmemlink::size() const
  0.00      4.79     0.00   432234     0.00     0.00
 ustl::cmemlink::cdata() const
  0.00      4.79     0.00   432233     0.00     0.00
 ustl::ios_base::rdstate() const
  0.00      4.79     0.00   432232     0.00     0.00
 ustl::getline(ustl::istringstream&, ustl::string&)
  0.00      4.79     0.00   432231     0.00     0.00  ustl::string::c_str()
const

The difference is in performance is too big between ustl (1min10s)/std
(10s) so for now I'll leave ustl on the category of nice to know but !

Anyway thanks for all of you and I hope I contributed a bit to this project.

Cheers !

**Comment by mingodad** [comment]
I started this to compare with a scripting language that I forked
https://github.com/mingodad/squilu and man the difference is too big:

std 10s  1.5MB memory
squilu 15s  6MB memory
ustl 1m10s 800KB memory

If a scripting language outperforms ustl maybe something is wrong !

Cheers !


foreach(fname in sqfs.dir(".")){
if(fname == "." || fname == "..") continue;
if(fname.endswith(".csv"))
{
print(fname);
local fd_in = file(fname, "r");
local fd_out = file(fname + "2", "w");
local quote_count = 0;
local line;
while( (line = fd_in.read_line(4096)) )
{
fd_out.write(line);
quote_count += line.count_char('"');
//accumulate quote count to check when we have a valid line
if( (quote_count % 2) == 0 )
{
fd_out.write("\n");
quote_count = 0;
}
}
fd_out.close();
fd_in.close();
break;
}
}

**Comment by msharov** [comment]
> If a scripting language outperforms ustl maybe something is wrong!

On any modern computer the main cause of performance problems is excessive IO. In uSTL streams case, the input buffer is only 256 bytes, which causes an order of magnitude more read calls than the scripting language does, where you explicitly set the buffer size to 4k (I assume that is what the read_line argument does). In uSTL, you can significantly improve performance by reading the whole file at once.
```c++
string filebuf;
filebuf.read_file (fname);
istringstream fd_in (filebuf);
// process lines as before
```
You can get count to inline by giving --force-inline flag to configure. This adds the always_inline attribute wherever the inline keyword is used, forcing the compiler to do as it is told. libstdc++ does the same thing in many places.

**Comment by mingodad** [comment]
It's not an option read the whole file in memory.
Here we have a clear fair comparison between std and ustl and now I changed
the scripting to load only 256 at a time, also applied --force-inline -O3
for ustl, each script run 3 times and I'm getting the best time:

std -> time ./clean-nl-inquotes
ted-contracts-2012.csv
Hello world! Alvarez

real 0m10.946s
user 0m1.480s
sys 0m2.824s

squilu -> time squilu-no-gui clean-nl-in-quotes.nut
ted-contracts-2012.csv

real 0m16.337s
user 0m6.023s
sys 0m7.169s

ustl -> time ./clean-nl-inquotes
ted-contracts-2012.csv
Hello world! Alvarez

real 0m49.415s
user 0m43.853s
sys 0m4.152s

So there is no doubt that ustl has an implementation performance problem !

It doesn't matter any tradeoff that requires more than twice performance
exchange at c/c++ level is too much.

Cheers !

**Comment by msharov** [comment]
I'm not interested in putting any work into this. If you wish to figure out how to improve performance, and if it does not result in too much codesize gain, I'll take it.

**Comment by msharov** [comment]
Commit 396c206ec2ce6f812dada3ec27b5eb27054823d6 increases ifstream/ofstream buffer size to 4k, which should significantly reduce system calls in your example.

**Comment by mingodad** [comment]
Well do you know this code better and just in case you can give some advice
on this:

profile for debug build static linked:
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 33.60     51.43    51.43 936788003     0.00     0.00  fill_n8_fast
 19.48     81.25    29.82   432232     0.07     0.34
 ustl::istringstream::get(ustl::string&, char)
 17.35    107.81    26.56 937220246     0.00     0.00
 ustl::string::resize(unsigned long)
 14.43    129.91    22.09 936788001     0.00     0.00
 ustl::string::append(unsigned long, char)
  5.01    137.58     7.67 937220244     0.00     0.00
 ustl::memblock::resize(unsigned long, bool)
  3.02    142.20     4.62                             main
  2.73    146.38     4.19 14644086     0.00     0.00  copy_n_fast
  1.02    147.94     1.56 937251259     0.00     0.00
 ustl::string::minimumFreeCapacity() const
  0.91    149.34     1.40  7322033     0.00     0.00  copy_backward_fast
  0.75    150.49     1.15  7322034     0.00     0.00
 ustl::ifstream::underflow(unsigned long)
  0.35    151.02     0.53        2   265.01   265.01
 ustl::string::append(char const*, unsigned long)
  0.32    151.51     0.49    31040     0.02     0.02
 ustl::memblock::unlink()
  0.22    151.85     0.34  7322037     0.00     0.00  rotate_fast
  0.19    152.14     0.30
ustl::string::hash(char const*, char const*)
  0.18    152.41     0.27        2   135.01   135.01
 ustl::string::string(unsigned long, char)
  0.12    152.60     0.19  7322038     0.00     0.00
 ustl::ofstream::flush()
  0.12    152.78     0.18  7322034     0.00     0.00
 ustl::fstream::readsome(void*, long)
  0.07    152.89     0.11  7353060     0.00     0.00
 ustl::cmemlink::link(void const*, unsigned long)
  0.03    152.94     0.05  7353079     0.00     0.00
 ustl::cmemlink::unlink()
  0.03    152.99     0.05  7322036     0.00     0.00
 ustl::istream::unlink()
  0.03    153.03     0.04   432232     0.00     0.34
 ustl::istringstream::getline(ustl::string&, char)
  0.01    153.04     0.02
ustl::utf8out_iterator<char*, wchar_t>::utf8out_iterator(char* const&)
  0.01    153.05     0.01   864465     0.00     0.00
 ustl::fstream::write(void const*, long)
  0.01    153.06     0.01
ustl::istream::istream(ustl::ostream const&)
  0.00    153.07     0.01
ustl::CBacktrace::stream_size() const

profile for -Os build static linked:
Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 32.15     14.03    14.03 936788003     0.00     0.00  fill_n8_fast
 20.81     23.11     9.08   432232     0.02     0.09
 ustl::istringstream::get(ustl::string&, char)
 11.23     28.01     4.90                             main
  8.33     31.65     3.64 936788001     0.00     0.00
 ustl::string::append(unsigned long, char)
  7.69     35.00     3.36 937220246     0.00     0.00
 ustl::string::resize(unsigned long)
  5.20     37.27     2.27 937220244     0.00     0.00
 ustl::memblock::resize(unsigned long, bool)
  4.03     39.04     1.76 14644086     0.00     0.00  copy_n_fast
  2.92     40.31     1.28  7322033     0.00     0.00  copy_backward_fast
  1.97     41.17     0.86 937251259     0.00     0.00
 ustl::string::minimumFreeCapacity() const
  1.19     41.69     0.52    31022     0.02     0.02
 ustl::memblock::reserve(unsigned long, bool)
  1.01     42.13     0.44
ustl::string::~string()
  0.83     42.49     0.36  7322038     0.00     0.00
 ustl::ofstream::flush()
  0.63     42.77     0.28        1   275.04   275.04
 ustl::string::append(char const*)
  0.58     43.02     0.26        2   127.52   127.52
 ustl::string::string(unsigned long, char)
  0.46     43.22     0.20  7322034     0.00     0.00
 ustl::ifstream::underflow(unsigned long)
  0.46     43.42     0.20  7322037     0.00     0.00  rotate_fast
  0.28     43.54     0.12  7322034     0.00     0.00
 ustl::fstream::readsome(void*, long)
  0.14     43.60     0.06
ustl::ostringstream::ostringstream(void*, unsigned long)
  0.05     43.62     0.02  7353060     0.00     0.00
 ustl::cmemlink::link(void const*, unsigned long)
  0.02     43.63     0.01   432232     0.00     0.09
 ustl::istringstream::getline(ustl::string&, char)
  0.02     43.64     0.01
ustl::CBacktrace::stream_size() const
  0.01     43.65     0.01                             fill_n16_fast
  0.00     43.65     0.00  7322036     0.00     0.00
 ustl::istream::unlink()

Cheers !

**Comment by msharov** [comment]
Commit 185ac581305bfb89f748ebb8c8e35014bc478cee rewrites istringstream::get to read in larger blocks.

**Comment by mingodad** [comment]
Hello !
Now it outperform std, thank so much, great job !
