### ISSUE TITLE
shared_ptr any reason to not have it ?

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#29]
Hello !
I noticed that ustl do not have a shared_ptr implementation, any reason for that ?
Then the next question would be atomic and threads ?

Cheers !

**Comment by msharov** [comment]
I do want to get shared_ptr done before the next release. Probably atomic too. I will not be doing threads, although I will take an implementation if you write one.

**Comment by mingodad** [comment]
Thanks !
I'm asking this because I'll try to compile https://github.com/loveyacper/Qedis with ustl to test both, actually qedis with std has a serious performance problem using std::list (mainly because of the std::list:size() and ustl uses vectors for lists).
Why qedis ? Because it's a rewrite of redis with c++ and I want to make a library with it so we can have a high performance low resource usage tcp server and a show case for ustl.

What I'm looking for is to have c++ as a kind of scripting language and for that a small performant library like ustl plus network, sqlite will be like writing scripting language code with c/c++ performance.

And I'll look at you casycom project it seems that can be an alternative to threads like go channels ?

Cheers !

**Comment by mingodad** [comment]
For thread I found this https://github.com/asmodehn/tinythreadpp it seems a good companion to ustl.

**Comment by msharov** [comment]
Commit 35f0e9514269268b777122acb95a093bdccbe2a7 implements atomic. As for threads, that will never work as long as implementation requires linking to pthread. Having libustl.so always linked to pthread is unacceptable; the vast majority of code is not and should not be multithreaded, and the extra footprint of pthread is larger than the entire uSTL shared library.

**Comment by mingodad** [comment]
Hello !
Is it possible to wrapp ustl::atomic with a preprocessor macro to not include it if needed ?
I'm trying to use a slight modified version of tinythreadapp https://github.com/mingodad/tinythreadpp and it was working till ust added atomic in=mplementation but without any hope to implement threads.

Cheers !

```
#ifndef NO_USTL_ATOMIC
namespace ustl
{
...
}
#endif //NO_USTL_ATOMIC
```

**Comment by msharov** [comment]
I will not be adding ifdefs to support one external project. You are already modifying tinythreadapp, so put ifdef USTL in there.

**Comment by mingodad** [comment]
Hello !
The atomic implementation is missing the add_fetch, sub_fetch, ...
Is this intentional ?
Cheers !

**Comment by msharov** [comment]
They are called fetch_add, fetch_sub, ...
http://www.cplusplus.com/reference/atomic/atomic/

**Comment by mingodad** [comment]
Ok thanks !
I only looked at the gcc atomic and was expecting explicit names for std.
But doing a test case for ustl::atomic I discovered that it's operator overloading is not working properly see example bellow (pre/pos increment operators).
When executed with std it prints :
    a0++ 0
    a0 1

When executed with ustl it prints :
    a0++ 1
    a0 0
```
#define USE_STD2
#ifdef USE_STD
#include <iostream>
#include <string>
#include <atomic>
#include <cassert>
using namespace std;
#else
#include <ustl.h>
using namespace ustl;
#endif // USE_STD

void testAtomic()
{
    {
        atomic<int64_t> a0;
        a0 = 0;
        assert(a0 == 0);
        cout << "a0++ " << a0++ << endl;
        cout << "a0 " << a0 << endl;
/*
        assert(a0++ == 0);
        assert(a0 == 1);
        assert((a0 +=2) == 3);
        assert(a0 == 3);
        assert(++a0 == 4);
        assert(a0 == 4);
        a0++;
        assert(a0 == 5);
        assert((a0 += -3) == 2);
        assert(a0.exchange(100) == 2);
        assert(a0 == 100);
    }

    {
        atomic<int32_t> a1;
        a1 = 0;
        assert(a1 == 0);
        assert(a1++ == 0);
        assert(a1 == 1);
        assert((a1 += 2) == 3);
        assert(a1 == 3);
        assert(++a1 == 4);
        assert(a1 == 4);
        a1++;
        assert(a1 == 5);
        assert((a1 += -3) == 2);
        assert(a1.exchange(100) == 2);
        assert(a1 == 100);
*/
    }
}

int main()
{
    testAtomic();
    string num, str = "Hello world!";
    //str.erase(str.begin(),1);
    str.erase(0,1);
    num += "0x10";
    cout << str << ":" << stoi(num, 0, 16) << endl;
    return 0;
}
```

**Comment by msharov** [comment]
It turns out there really are undocumented add_fetch, sub_fetch, etc. members, and that they are needed. Commit 910f5538367b7e5e665aa083d2ff6fc3887665d0.

**Comment by mingodad** [comment]
Hello !
I'm trying to compile https://github.com/measurement-factory/http-paxxer with ustl and noticed that the shared_ptr brother weak_ptr is no implemented in ustl. Any chance of have it ?
Cheers !

**Comment by msharov** [comment]
No. weak_ptr is fundamentally a bad idea. Not only does it make shared_ptr implementation considerably more complex, but it is in itself an indication of bad design. Every design *must* define object ownership and lifetime, or suffer the consequence of never knowing what the program is actually doing. shared_ptr is a way to avoid defining object ownership and is usually a bad idea too, but there are circumstances where careful use can be correct. weak_ptr avoids defining object lifetime; it is essentially a formalized dangling reference, and whenever you see it **burn it with fire**! Fix your design. Create a rigid specification on who owns each object and the exact boundaries where each object is created and destroyed. Then ensure that the calling code can not violate those boundaries. Any code that does not do this is bad. weak_ptr is a sure sign of such bad code. Do not use it.

**Comment by mingodad** [comment]
Have you heard of "circular reference" ?
How to avoid it with your too strict rules ?

**Comment by msharov** [comment]
Circular references are also a sign of bad design. Remove them. If for some reason you can not, the owner of the objects must ensure that the circularly referenced objects are created and destroyed together. The references themselves would be stored as regular pointers. This is safe because once you define the linked object lifetimes to be the same, by creating and destroying them together, there will never be any danger of those pointers dangling.

**Comment by mingodad** [comment]
What is using your solution to this http://oopscenities.net/2014/08/03/c-smart-pointers-part-5-weak_ptr/ ?

**Comment by msharov** [comment]
The example you reference builds a tree with child nodes pointing to parent nodes. In this example, the most serious problem is the use of shared_ptr in the first place. Node ownership must be defined first, by the tree container. Then node lifetime must be considered. Can a child node exist once its parent node has been deleted? *No!* Nodes are deleted only through the container's interface and whenever a node is deleted, all its child nodes are deleted as well. Once node lifetime is thus linked to its parent node's, it is perfectly acceptable to use a plain pointer to it.

smart_ptr in general should not be used. I do remember coming up with a few valid examples for it, but I can't think of any right now. The whole idea of putting objects "up in the air" like this is fundamentally wrong. Objects should always be owned by a container object. That way you always know who owns the object and can control its lifetime. Those are the necessary preconditions for knowing what your program is doing - for good design.
