### ISSUE TITLE
STDUNIX_HEADERS not set on Debian?

### ISSUE THREAD

**Issue by mwarning** [msharov/ustl#3]
Hi,

I tried ustl v2.2 on Debian (8.0). ./configure ran fine, but make got me this error:

    ustl-2.2$ make
        Compiling sostream.cc ...
    In file included from uutility.h:10:0,
                     from ualgobase.h:7,
                     from cmemlink.h:7,
                     from memlink.h:7,
                     from mistream.h:7,
                     from sostream.cc:6:
    utypes.h:12:6: error: #error "This library compiles only on UNIX systems."
         #error "This library compiles only on UNIX systems."
          ^
    Makefile:48: recipe for target '.o/sostream.o' failed
    make: *** [.o/sostream.o] Error 1

**Comment by mwarning** [comment]
Ok, to define HAVE_SYS_STAT_H in config.h did the job.
But I wonder why the configure script does not see that  <sys/types.h> exists (/usr/include/linux/types.h).

**Comment by msharov** [comment]
HAVE_SYS_STAT_H is defined for /usr/include/sys/stat.h, which contains definitions for fstat and friends. Please check that you have that header. If not, perhaps you should check if your glibc package is correctly installed. apt should have some means of verifying a package ( I've never used a Debian-type distribution, so I just don't know)

**Comment by mwarning** [comment]
/usr/include/sys/stat.h does not exist.
But the file is included is /usr/include/x86_64-linux-gnu/sys/stat.h.

```gcc -xc++ -E -v -``` gives me:

 /usr/include/c++/4.9
 /usr/include/x86_64-linux-gnu/c++/4.9
 /usr/include/c++/4.9/backward
 /usr/lib/gcc/x86_64-linux-gnu/4.9/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include

There is the same problem on a fresh Debian (7.7) install.
I think I need to figure out how the paths are aquired by configure.

**Comment by msharov** [comment]
Ok, then this is definitely a won't fix. I am frankly appalled by the disrespect some of these Debian derivatives show to the UNIX philosophy. Headers *must* be in /usr/include somewhere, and system headers *must* be in there. If you want platform-specific stuff for the non-native platform (the native platform being that for which your distribution is built), put it in /usr/platform. In this case, however, x86_64 is the native platform, and your distribution is engaging in 64-bit hate, pretending that x86_64 is just some addon to i386 that will hopefully go away soon. I absolutely refuse to pander to this abomination, and my only reply to people having problems with these distributions is to use another distribution. My projects are only for UNIX-based systems.

That said, you can specify ./configure --includedir=/usr/include/x86_64-linux-gnu , or --oldincludedir to work around this problem.

**Comment by mwarning** [comment]
*./configure --includedir=/usr/include/x86_64-linux-gnu* did work, thanks.

**Comment by msharov** [comment]
Ok, one more comment is needed. After finally succumbing to the pressure of adding the platform directories by default in configure, I'm reverting the change because it is inconsistent with system policy; libustl and the headers are still installed in /usr/lib and /usr/include. There is no way to reliably detect that the /usr/lib/platform scheme is being used, so configure can not automatically do this. So the final official fix is that configure must be run with --includedir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu so that the dependencies are found and uSTL is also installed where the system expects libs and headers to be.
