### ISSUE TITLE
string::erase overload bug ?

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#32]
Hello !

I'm testing ustl on https://github.com/titi38/libnavajo and one of the errors I'm getting is this one:

```
#include <ustl.h>
using namespace ustl;

int main()
{
    string str = "Hello world!";
    str.erase(0,1);
    cout << str << endl;
    return 0;
}
```
```
||=== Build: Debug in test (compiler: GNU GCC Compiler) ===|
main.cpp||In function ‘int main()’:|
main.cpp|7|error: call of overloaded ‘erase(int, int)’ is ambiguous|
main.cpp|7|note: candidates are:|
../../../../../../local/include/ustl/ustring.h|163|note: ustl::string::value_type* ustl::string::erase(ustl::string::const_iterator, ustl::cmemlink::size_type)|
../../../../../../local/include/ustl/ustring.h|164|note: ustl::string& ustl::string::erase(ustl::cmemlink::size_type, ustl::cmemlink::size_type)|
../../../../../../local/include/ustl/ustring.h|165|note: ustl::string::value_type* ustl::string::erase(ustl::string::const_iterator, ustl::string::const_iterator) <near match>|
../../../../../../local/include/ustl/ustring.h|165|note:   no known conversion for argument 2 from ‘int’ to ‘ustl::string::const_iterator {aka const char*}’|

```

**Comment by msharov** [comment]
uSTL has nonstandard behavior here in that it supports iterator offsets, as well as numeric offsets. Iterator offsets ensure functionality similar to vector, and their implementation predates the numeric versions. So, by design.

**Comment by mingodad** [comment]
Just in case it help others !
I found that the problem only happen with the first parameter to erase been 0, any other value (1,2,...) works and with a qualified 0ul it also works.

**Comment by msharov** [comment]
If you use 0u instead of 0, the compiler will know you are not trying to use a null pointer.

**Comment by mingodad** [comment]
Well maybe you said that without actually try it, here with g++ and the simple example above if we try to use erase(0u, 1) we still get the same error.
Cheers !

**Comment by msharov** [comment]
Huh? This used to be the way to resolve this ambiguity. I can't find where that changed, although I do recall fixing some bug about npos that may have broken things.

**Comment by mingodad** [comment]
Now it work with numbers alone and we can switch between std/ustl without problems.
Thanks so much for your great work and time !
