### ISSUE TITLE
ustl::getline is missing default parameter

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#33]
Hello !
I finally got one project in dual mode std/ustl it's at https://github.com/mingodad/libnavajo , to make it work several small changes were made and one of then was to ustl itself, the std/ustl::getline function has an optional parameter to specify the delimiter and it is missing in ustl.

sistream.h
/// Reads a line of text from \p is into \p s
inline istringstream& getline (istringstream& is, string& s, char delim = '\n')
    { return is.getline (s, delim); }

If someone want to try that project with ustl there is a codeblocks project there for it.
Cheers !

**Comment by msharov** [comment]
Commit 57f27167cecff5ee0a7dc5f78cb44f5ac9efd4e2. But really, you should not be using the unscoped getline. Use the stream member function.
