### ISSUE TITLE
ustl missing forward_iterator_tag, bidirectional_iterator_tag, ...

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#37]
Hello !
Doing experiments with ustl I found that the ustl::list (using vector) has a performance toll for insertions/deletions (except at the tail) then I found http://en.literateprograms.org/Unrolled_linked_list_%28C_Plus_Plus%29 and decided to try adapt it to ustl, but ustl do not have some iterator features like forward_iterator_tag, bidirectional_iterator_tag and I can not compile it yet.
But I could run the original benchmark and adapted to run the same benchamark for ustl:
```
std -> ./perf-test
test_push_back< std::list<int> >: 4.263308
test_push_back< std::vector<int> >: 1.169714
test_push_back< unrolled_list<int,1024> >: 0.355661
test_push_back< unrolled_list<int,128> >: 0.591150
test_push_front< std::list<int> >: 0.043301
test_push_front< std::vector<int> >: 49.488319
test_push_front< unrolled_list<int,1024> >: 0.117148
test_push_front< unrolled_list<int,128> >: 0.020660
test_iteration< std::list<int> >: 1.491637
test_iteration< std::vector<int> >: 0.065647
test_iteration< unrolled_list<int,1024> >: 0.131033
test_iteration< unrolled_list<int,128> >: 0.247265

ustl -> ./perf-test-ustl
test_push_back< ustl::list<int> >: 0.536084
test_push_back< ustl::vector<int> >: 0.500690
test_push_front< ustl::list<int> >: 94.054572
test_push_front< ustl::vector<int> >: 93.953554
test_iteration< ustl::list<int> >: 0.072678
test_iteration< ustl::vector<int> >: 0.071577
``` 
The ustl vector/list takes twice as much std::vector and more than 900 times as much std::list (both for push_front).

There is any reason to not have forward_iterator_tag, bidirectional_iterator_tag implemented ?

Attached is the adapted unrolled_list to work with ustl.

[Uploading unrolled_list.zip…]()

**Comment by msharov** [comment]
uSTL does not support linked containers of any kind or non-pointer iterators. They are never appropriate on modern architectures due to the way memory caching works and should never be used. If your test case requires performance when inserting in the middle, you should redesign your test case, or use a database with a B-tree.

**Comment by msharov** [comment]
On second thought, there is no reason not to add iterator_category anyway. It does no harm.

**Comment by mingodad** [comment]
Hello !
I finally got it to compile with ustl, the problem basically was ustl is missing a declaration of:
```
template<class Category, class T, class Distance = ptrdiff_t,
         class Pointer = T*, class Reference = T&>
struct iterator
{
    typedef T         value_type;
    typedef Distance  difference_type;
    typedef Pointer   pointer;
    typedef Reference reference;
    typedef Category  iterator_category;
};
```
And it seems ustl do not have non const iterators, so on the test program I changed a non const iterator by a const_iterator and it compile fine.

The results are still similar to showed before (ustl list/vector do not perform well for push_front):
```
ustl build -> ./perf-test
test_push_back< ustl::list<int> >: 0.581510
test_push_back< ustl::vector<int> >: 0.600351
test_push_back< unrolled_list<int,1024> >: 0.340733
test_push_back< unrolled_list<int,128> >: 0.483511
test_push_front< nw::list<int> >: 93.911408
test_push_front< nw::vector<int> >: 93.895085
test_push_front< unrolled_list<int,1024> >: 0.121511
test_push_front< unrolled_list<int,128> >: 0.023408
test_iteration< ustl::list<int> >: 0.072698
test_iteration< ustl::vector<int> >: 0.072605
test_iteration< unrolled_list<int,1024> >: 0.129507
test_iteration< unrolled_list<int,128> >: 0.265299

std build -> ./perf-test
test_push_back< nw::list<int> >: 4.266725
test_push_back< nw::vector<int> >: 1.107632
test_push_back< unrolled_list<int,1024> >: 0.353394
test_push_back< unrolled_list<int,128> >: 0.599176
test_push_front< nw::list<int> >: 0.043648
test_push_front< nw::vector<int> >: 45.305423
test_push_front< unrolled_list<int,1024> >: 0.116999
test_push_front< unrolled_list<int,128> >: 0.020758
test_iteration< nw::list<int> >: 1.492283
test_iteration< nw::vector<int> >: 0.061217
test_iteration< unrolled_list<int,1024> >: 0.129109
test_iteration< unrolled_list<int,128> >: 0.244675
```
Attached is the final code just in case someone else want to see it.

Cheers !

[Uploading unrolled_list-ustl.zip…]()
