### ISSUE TITLE
istrean missing gcount method

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#42]
Hello !
I'm trying to test ustl with https://github.com/duckduckgo/cpp-libface and noticed that ustl::istream is missing the ustl::istream::gcount() method that is present in std.
Can it be added ?

This method is used mainly when we want limit the length read by get_line:
```
#define INPUT_LINE_SIZE 256
char buf[INPUT_LINE_SIZE];
is.get_line(buff, INPUT_LINE_SIZE);
streamsize line_length = is.gcount();
if(line_length == -1) done();
```

**Comment by msharov** [comment]
Later.
