### ISSUE TITLE
Make check issue with the current branch

### ISSUE THREAD

**Issue by dfateyev** [msharov/ustl#50]
Got a small problem while testing the current snapshot:
```
$ ./configure
$ make
    Linking inplace header location ...
    Compiling sostream.cc ...
    ...
Linking libustl.so.2.3 ...

$ make check
mkdir: cannot create directory '.o/bvt': File exists
bvt/Module.mk:50: recipe for target '.o/bvt/.d' failed
make: *** [.o/bvt/.d] Error 1
```

**Comment by msharov** [comment]
Could you please describe what you did to make this happen? .o/bvt and .o/bvt/.d are always created and removed together. It should not be possible to have one without the other.

**Comment by dfateyev** [comment]
OK, I got this. The `"make"` call creates and uses the directory `/tmp/mock/make/ustl` (in my case) so `"make check"` creates `bvt` there. The problem occurs when this temp dir isn't removed after all. While running `"make"` the second time we use the same dir, rebuild `ustl` without issues, but already have `bvt` dir there from the previous attempt, and dir creation is failing as above.
The solution would be removing temp dir or flushing its content before `ustl` lib build in `"make"`.

**Comment by msharov** [comment]
Well, just goes to show that if you try really hard, you can find a way to make the build fail :) This is not a bug though.

**Comment by dfateyev** [comment]
Well, it actually barely affects me ;-) I make builds in separate build env-s so never faced it before. Noticed this only occasionally running build several times under a "real user".
