### ISSUE TITLE
segmentation fault in ustl replace algorithm

### ISSUE THREAD

**Issue by andrey-zibrov** [msharov/ustl#56]
Hi, please help to solve that issue or give your recomendations.

```
#ifdef USE_USTL
#include <ustl.h>
#define STL ustl
#else
#include <string>
#include <algorithm>
#include <iostream>
#define STL std
#endif //USE_USTL

#include <string.h> //strlen

#define PRINT(X) STL::cout<<X<<STL::endl
int main()
{
    char Str[]="test";
    PRINT("char * testing: "<<Str);
    STL::replace(Str,Str+strlen(Str),'t','z');
    PRINT("char * testing: "<<Str);

    STL::string Strng="test";
    PRINT("string testing: "<<Strng);
    STL::replace(Strng.begin(),Strng.end(),'t','z');
    PRINT("string testing: "<<Strng);
}

```

$ g++ replace.cxx -o replace.x
$ ./replace.x 
char * testing: test
char * testing: zesz
string testing: test
string testing: zesz
$ g++ replace.cxx -DUSE_USTL -lustl -o replace.x
$ ./replace.x 
char * testing: test
char * testing: zesz
string testing: test
Ошибка сегментирования (core dumped)

$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)

**Comment by msharov** [comment]
This is intentional. Please read the string section on the uSTL documentation page. uSTL strings constructed on const char* will create a linked string. Use the explicit operator= to create a writable string as below.
``` C++
STL::string Strng;
Strng = "test";
```

**Comment by andrey-zibrov** [comment]
thank you!)
