### ISSUE TITLE
ostringstream::capacity() const is protected

### ISSUE THREAD

**Issue by andrey-zibrov** [msharov/ustl#59]
why?
we got public max_size()
but protected capacity()
what for?

how to get stream buffer.capacity()? (while it's just a string in ustl)

example:

```
ustl::string Something(){/*...*/}
ustl::ostringstream stream;
stream<<ustl::ios::width(6)<<Something();

const ustl::string ex(stream.str(),stream.capacity()); //just example
```

just need to use a backward compatible following way 

g++ code.cxx -o code.x
and
g++ code.cxx -o code.x -DUSE_USTL -lustl

to get same behaviour

**Comment by msharov** [comment]
The stream has no capacity. The stream buffer has a capacity. Use stm.str().capacity(). max_size() ought to be removed, but since it has been there for a long time, that would be undesirable.
