### ISSUE TITLE
ostringstream::flush() returns &ostream

### ISSUE THREAD

**Issue by andrey-zibrov** [msharov/ustl#60]
Is it correct to return *this for an object of a direved class as a reference of a base class?
looks like it does a "section slicing" of on object from a direvied class to a base class.
the downcasting in such line can lead to an unsafe operation.

other ostringstream methods are returning *this as a ostringstream reference.

**Comment by msharov** [comment]
While it would indeed be a correct thing to do, it is impossible with the current design where flush is a virtual function, overriden from ostream, and thus must retain ostream& return type.
