### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by MrLonko** [msharov/ustl#64]
Your library is perfect for use in embedded world. Why don't you make support for crosscompiling?

Or at least make an option to import what test program outputs while manually ran on embedded target.
This library has a VERY high potential on embedded targets.

Would that be possible?

**Comment by msharov** [comment]
As I have stated many times, I have no interest in embedded platforms. In my opinion, developing for them is a waste of time; they come and just as quickly vanish. By the time you finish developing your app, the world moves on to a new platform and you have to start from scratch. See mention of Symbian below. And then there is the issue of their complete uselessness. I have an Android smartphone gathering dust in my desk drawer. In all the years I have had it, I have found no use for it.

In addition to this lack of interest on my part, I also lack the money required to acquire and test builds on the great multitude of embedded platforms in existence at any given time. If I can not test that a feature is working, I am not going to include it in the library.

If you have the necessary hardware and are willing to do the testing, you are welcome to fork uSTL and make it work there. See, for example, the fork for the Symbian OS. Symbian, has been dead for nearly a decade now, just as I kept saying it would be, but the uSTL fork is still around, presumably with somebody wasting time on supporting it.
