### ISSUE TITLE
missing std::function

### ISSUE THREAD

**Issue by grynca** [msharov/ustl#69]
are you planning on including custom implementation of std::function for ustl ?
Something like this?
https://probablydance.com/2013/01/13/a-faster-implementation-of-stdfunction/
I tried to modify it for using with ustl but failed. (it is crawled with stl code - mainly for custom allocators)
Thanks for response in advance.

**Comment by msharov** [comment]
std::function is probably the single most complicated piece of code in all of STL. It is also one of the least useful. I can't think of any situation where I would want to use it, and consequently have no interest in working on it. I would instead recommend you use the function implementation in the boost library.
