### ISSUE TITLE
istringstream stuck

### ISSUE THREAD

**Issue by andrey-zibrov** [msharov/ustl#72]
Hi Mike,

why is this code getting stuck at the >> operator?  

#include "lustl.h"

#define PRINT(X) ustl::cout<<X<<ustl::endl

`int main()`
`{`
`	ustl::string x;`
`	x.assign("123");`
`	ustl::istringstream a(x);`
	
`	PRINT(x);`
`	PRINT(a.str());`

`	unsigned u=0;`
`	//a.get();`
`	a>>u;`
`	PRINT(u);`
`	return 0;`
`}`

it shows only:
123
123
and hangs...

**Comment by andrey-zibrov** [comment]
actually i wanted to implement something like this:
` 	template <typename T>`
` 	static bool IsStringCastsTo(T & rxResult, const StringType &rcsSourceString, STL::ios::base _base = STL::ios::base(10))`
` 	{`
` 		STL::istringstream xTemp(rcsSourceString);`
` 		return !(xTemp >> _base >> rxResult).fail() && xTemp.eof();`
` 	}`

i was forced to add a:
`inline void     text_read (istringstream& is) const { is.setf(_f, basefield); }` to a ustl::ios::strcut base
but i found that example listed above not works with / without my fix.. but test still does. What i am doing wrong?

**Comment by andrey-zibrov** [comment]
Mike, what should i investigate firstly at by my self in this case?

**Comment by msharov** [comment]
Fixed by 19ca7aa7d5497908c4c1da0cb4ca31ce374d8f36
