### ISSUE TITLE
(istringstream::operator >> bool).fail() always false

### ISSUE THREAD

**Issue by andrey-zibrov** [msharov/ustl#73]
ustl fail() always return false

`#include "lustl.h"`
`#include "stdio.h"`

`void boolf()`
`{`
`	STL::string rcsSourceStringFalse; rcsSourceStringFalse.assign("false");`
`	STL::string rcsSourceStringTrue; rcsSourceStringTrue.assign("true");`
`	STL::istringstream xTempF(rcsSourceStringFalse);`
`	STL::istringstream xTempT(rcsSourceStringTrue);`
`	bool bt,bf,refBoolResultT,refBoolResultF;`
`#ifdef USE_USTL //ustl`

`	xTempF.setf(STL::istringstream::boolalpha);` //loolks like this isn't matter?
`	bf =(!(xTempF>> refBoolResult).fail());`
`	bf = bf && xTempF.eof();`
`	xTempT.setf(STL::istringstream::boolalpha);`
`	bt =(!(xTempT>> refBoolResult).fail());`
`	bt = bt && xTempT.eof();`
`#else //or std`

`	bf =(!(xTempF>> STL::boolalpha >> refBoolResult).fail());`
`	bf = bf && xTempF.get();`
`	bf = bf && xTempF.eof();`
`	bt =(!(xTempT>> STL::boolalpha >> refBoolResult).fail());`
`	bt = bt && xTempT.get();`
`	bt = bt && xTempT.eof(); //switches to a false without calling get()....0_o`
`#endif //USE_USTL`

`	printf("%d %d %d %d\n",bt,bf,refBoolResultF,refBoolResultT);`
`}`

user@my-vm:/home$ clang++ istrm.cpp -o istrm.clang++.ustl.x -DUSE_USTL -lustl
user@my-vm:/home$ ./istrm.clang++.ustl.x 
0 0 0 1
user@my-vm:/home$ g++ istrm.cpp -o istrm.g++.ustl.x -DUSE_USTL -lustl
user@my-vm:/home$ ./istrm.g++.ustl.x 
0 0 0 1
user@my-vm:/home$ clang++ istrm.cpp -o istrm.clang++.stl.x
user@my-vm:/home$ ./istrm.clang++.stl.x 
1 1 0 1
user@my-vm:/home$ g++ istrm.cpp -o istrm.g++.stl.x
user@my-vm:/home$ ./istrm.g++.stl.x 
1 1 0 1

**Comment by msharov** [comment]
failbit is set on input errors, such as read failure in fstream. istringstream can not have any of those, so it never sets it. It does set eof, which is what you should be checking to detect the end of stream - that's why it is there.

**Comment by andrey-zibrov** [comment]
xTempF.setf(STL::istringstream::boolalpha);
	bf =(!(xTempF>> refBoolResultF).fail());
	//xTempF.get();
	//bf = bf && xTempF.eof();
	xTempT.setf(STL::istringstream::boolalpha);
	bt =(!(xTempT>> refBoolResultT).fail());
	//xTempT.get();
	//bt = bt && xTempT.eof();

nothing changed.
fail() still returns non-zero
