### ISSUE TITLE
istringstream read bool does not treat EOF as a non-read delimiter

### ISSUE THREAD

**Issue by andrey-zibrov** [msharov/ustl#74]
please add / extend more sense for your point of view
(sorry about reopen if it harms you side)
i agree that ustl::istringstream can't/should't contain any failbits in this case
but i also agree with the same interface and behavior between std and ustl (please fix me if i'm wrong) 

my latest comment at #73  mentions that i had retested original case without adding eof() to result.

it is checking only fail() result;

std:

user@my-vm:/home$ clang++ istrm.cpp -o istrm.clang++.std.x -I ../COMMON/
user@my-vm:/home$ ./istrm.clang++.std.x 
passed: "false", actual result: '0', expected result: '0', logical complete result: **_1_**
passed: "true", actual result: '1', expected result: '1', logical complete result: **_1_**

ustl:

user@my-vm:/home$ clang++ istrm.cpp -o istrm.clang++.ustl.x -I ../COMMON/ -DUSE_USTL -lustl
user@my-vm:/home$ ./istrm.clang++.ustl.x 
passed: "false", actual result: '0', expected result: '0', logical complete result: **_0_**
passed: "true", actual result: '1', expected result: '1', logical complete result: **_0_**

invalid "logical complete" result blocks trusting to ">> operation" from user side.
so as a workaround user has to convert "actual result" vise-versa to a temporary string again to do a custom check of convertion

g++ has the same results

please take a look at attachment
[istrm.cpp.txt](https://github.com/msharov/ustl/files/831918/istrm.cpp.txt)

**Comment by andrey-zibrov** [comment]
also other scalar types

**Comment by msharov** [comment]
On futher examination of your problem I find that the issue is that istringstream reads the bool string until it finds a delimiter. Because you do not provide a delimiter in the string, it reads past end of file to determine that it needs to stop. This is consistent with how it reads other types, such as string, where it will read EOF as a delimiter. Once EOF is read, eof and fail are set. Fail is set because istringstream requires the delimiter, and is unable to find one. I believe that this is appropriate and am not going to change this behavior. You can simply ignore the fail bit if you insist on reading undelimited things at EOF.

**Comment by andrey-zibrov** [comment]
that make sense. thanks alot

**Comment by andrey-zibrov** [comment]
i just left the following code here, just to show how to ignore that behavior in a common way (there is no problem to create a non-copy variant):

    template <typename T>
    static bool IsStringCastsTo(T & rxResult, const StringType &rcsSourceString, size_t iBase=10)
    {
        bool bLogicResult = false;
        STL::istringstream xTemp(rcsSourceString);
        T tempValue;

        #ifdef USE_USTL
          STL::ios::base _base(iBase);
          xTemp.setf(STL::istringstream::boolalpha);
          bLogicResult = !(xTemp >> _base >> tempValue).fail();
          if(!bLogicResult){
          /*<there is a workaround below since https://github.com/msharov/ustl/issues/74 sugggested a non-standard handling of bool>*/
            STL::ostringstream xTemp2;
            xTemp2.setf(STL::istringstream::boolalpha);
            xTemp2<<tempValue;
            bLogicResult = xTemp.str() == rcsSourceString;
          }/*</workaround>*/
        #else
          bLogicResult = !(xTemp >> STL::boolalpha >> STL::setbase(iBase) >> tempValue).fail();
        #endif //USE_USTL
        xTemp.get();

        if((bLogicResult = bLogicResult && xTemp.eof()))
        {
            rxResult = tempValue;
        }

        return bLogicResult;
    }

**Comment by msharov** [comment]
istringstream is not designed to do validity checking on the input. It will be just fine in saying that "true not 1" will convert to a bool, or that "123 what?" will convert to an int, even though that is nonsense. You will have to explicitly verify that the string contains appropriate contents. For example, to read bool, compare with "true" and "false". To read int, verify that only digits are present. Etc. There is no way to avoid doing that work.

**Comment by andrey-zibrov** [comment]
ok. i just found that g++/clang++ raises up .fail() with true if i'm trying to convert string("some true") to a bool, but not a string("true"). or if i'm trying to convert a "0xffff" to T (which is float at this moment) (i can't know it and where i am on runtime where )... And for other user types i already have that checking that you has  mentioned.

**Comment by msharov** [comment]
You will still not get a fail on "true lies". Instead of the hair-raising tangle you have created with istringstream, a simple template spec and compare is better:
```c++
template <>
static bool IsStringCastsTo(bool&, const StringType& s, size_t)
    { return s == "true" || s == "false"; }
```

Or, better yet, stop trying to reinvent the wheel, poorly, and just use
[boost::any](http://www.boost.org/doc/libs/1_63_0/doc/html/any.html).

**Comment by andrey-zibrov** [comment]
yes, for a bool this spec is good. 
i don't like boost at all. i got too tiny target for it. i'm trying to design some project that might work (already works fine) on Win/Mac/iOS/Android/Odroid/Any ARM linux targets and the smallest of them doesn't need this huge library. uSTL features are absolutely matched with my purposes, and  IsStringCastsTo is just one of the bicycles from a huge cross-platform tool library which is a HardwareAbstractionLayer (bindings) for the whole project.

anyway thank your for your attention. string2bool question is closed for my side.
