### ISSUE TITLE
`make clean` tries to remove /tmp

### ISSUE THREAD

**Issue by darealshinji** [msharov/ustl#75]
```
$ make clean 
rmdir: failed to remove directory '/tmp'
Makefile:124: recipe for target 'clean' failed
make: *** [clean] Error 1
```

**Comment by msharov** [comment]
Which platform is this on? rmdir --ignore-fail-on-non-empty flag should have eliminated this error.

**Comment by darealshinji** [comment]
Ubuntu 16.04 x86_64 with GNU coreutils 8.25, which should support `--ignore-fail-on-non-empty`.

**Comment by msharov** [comment]
So that leaves the question, does Config.mk still have the flag on rmdir (see line 23, RMPATH definition) ? Alternatively, is your /tmp actually empty? At the least, the X sockets should be in there in /tmp/.X11-unix .

**Comment by darealshinji** [comment]
From Config.mak:
```
RMPATH		:= rmdir -p --ignore-fail-on-non-empty
```

And no, it's not empty.

**Comment by msharov** [comment]
Well, then I just don't know. It'll just have to put back the > /dev/null || true then...
