### ISSUE TITLE
lack of filesystem support library

### ISSUE THREAD

**Issue by GravisZro** [msharov/ustl#78]
The filesystem support library is new in C++17 but it too can easily be implemented by using POSIX which is supported on the most platforms.

**Comment by msharov** [comment]
The filesystem support library seems to be just another excessively bloated and verbose C++ wrapper from the "ALL C FUNCTIONS ARE BAD" people. Just like the locale classes, it may not necessarily be a bad idea, but it sure is a rotten implementation. In its present form, I do not want it in uSTL.

**Comment by jwakely** [comment]
> The filesystem support library seems to be just another excessively bloated and verbose C++ wrapper from the "ALL C FUNCTIONS ARE BAD" people.

No, it has nothing to do with C functions. The point is that there are no portable C functions that work on both POSIX and Windows. `<filesystem>` provides a portable abstraction. If you only care about POSIX then you don't need it.
