### ISSUE TITLE
shared_ptr::swap is broken

### ISSUE THREAD

**Issue by coder4322342** [msharov/ustl#81]
https://github.com/msharov/ustl/blob/40c87b517539f45428d6997b78fd889682c3f935/umemory.h#L84

At `swap (_p, v._p)`: This should call `ustl::swap` but instead attempts to call itself (`this->swap`). Since there is no matching `shared_ptr::swap` this results in a compiler error.

Since this is an inline function the issue will likely only present itself if you call `shared_ptr::swap` (or the `shared_ptr` move constructor).

**Comment by coder4322342** [comment]
Since this is an inline function the issue will only only present itself if you call `shared_ptr::swap` (or the `shared_ptr` move constructor).

**Comment by msharov** [comment]
I am unable to reproduce any problems with shared_ptr::swap. Please attach specific failing code, compiler version, and the exact error message received.
