### ISSUE TITLE
configure --without-mmx

### ISSUE THREAD

**Issue by hoangmle** [msharov/ustl#82]
I need to build ustl on x86-64 without any inline asm (for an exotic application). This was partly supported in the past by the option --without-mmx. This option has no effect now

**Comment by msharov** [comment]
without-mmx never did disable all inline assembly. It only disabled MMX and SSE assembly. You can do that now by editing TGTOPTS in Config.mk, adding -mno-sse and -mno-mmx compiler flags. There is generally no reason to do this any more; the assembly has been in use for over a decade with no problems, and thus is likely to be working correctly. Consequently, configure no longer supports the disabling option.

You will still get other x86-based assembly here and there. Most can be disabled by commenting out __x86__ definition in config.h. Two other functions, bswap_64 and FirstBit uint64_t, depend directly on __x86_64__. They are inline, so if you do not use them, they will not be compiled. As with SSE, nobody should need to do this, so no configure option is provided.
