### ISSUE TITLE
integration in other projects...

### ISSUE THREAD

**Issue by asmodehn** [msharov/ustl#83]
Have you consider providing a more modern way to integrate ustl in other build workflows ?
Some kind of package manager (conan, hunter, etc.), or build integration (cmake, etc.) or source download (cmake, other) ?

Currently I understand the best way to integrate ustl in a C++ project, would be to somehow link with autotools and use the ustl as a git submodule, correct ?

I am currently thinking of upgrading my C++ toolchain, and ustl is one of my dependencies.

Any preference / advice on that topic ?

**Comment by msharov** [comment]
Making packages is the task for distribution maintainers. They usually have their own requirements for how that is to be done and their own collection of build scripts. Packaged projects, such as uSTL, hardly ever provide packaging as part of a release. And they should not.

As for "integrating" uSTL into a C++ project, it is no different than any other library. You install the library, using a package manager or just `make install`, and then link to it. The usual way to discover what to link to is to read documentation. uSTL documentation clearly explains how it is to be done. uSTL also supports `pkg-config` for cflags and libs discovery.

Embedding uSTL in your project is not appropriate if you are not modifying the library itself. Your git repository should only contain code that you yourself are working on.
