### ISSUE TITLE
Failed to compile fast-cpp-csv-parser

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#88]
Hello !
I'm evaluating ustl again against several opensource projects to see how well it can be to replace libstdc++ for average project and found some problems when trying to compile https://github.com/ben-strasser/fast-cpp-csv-parser .
As with other projects that I've tried the general changes are, adding a preprocessor macro to be able to switch between ustl and std and replace all usage of "std::" by "lstd::".

```
#ifdef WITH_USTL
#include <ustl.h>
namespace lstd=ustl;
#else
#include <iostream>
namespace lstd=std;
#endif
```
In this project the main errors are:
```
In file included from test.cpp:1:0:
csv.h: In member function ‘virtual int io::detail::NonOwningIStreamByteSource::read(char*, int)’:
csv.h:175:43: error: ‘class ustl::istream’ has no member named ‘gcount’
                                 return in.gcount();
```
It seems that std have "gcount()" in std::basic_istream::gcount but ustl has it only in upper derived classes.

```
In file included from test.cpp:1:0:
csv.h: In member function ‘bool io::detail::SynchronousReader::is_valid() const’:
csv.h:302:52: error: no match for ‘operator!=’ (operand types are ‘const ustl::unique_ptr<io::ByteSourceBase>’ and ‘std::nullptr_t’)
                                 return byte_source != nullptr;
```
It seems that ustl is missing some operator overloading.
```
csv.h: In constructor ‘io::CSVReader<column_count, trim_policy, quote_policy, overflow_policy, comment_policy>::CSVReader(Args&& ...)’:
csv.h:1137:76: error: call of overloaded ‘to_string(unsigned int&)’ is ambiguous
                                 column_names[i-1] = "col"+lstd::to_string(i);
```
Again it seems that ustl is missing some operator overloading.
```
In file included from test.cpp:1:0:
csv.h: In member function ‘bool io::CSVReader<column_count, trim_policy, quote_policy, overflow_policy, comment_policy>::has_column(const ustl::string&) const’:
csv.h:1183:52: error: ‘begin’ is not a member of ‘lstd’
                                         lstd::find(lstd::begin(column_names), lstd::end(column_names), name)
```
Again it seems that ustl is missing some iterator overloading.

Attached is a copy of the modified project with a script that compiles it for std (working) and ustl (not working because of the errors mentioned).
[fast-cpp-csv-parser.zip](https://github.com/msharov/ustl/files/2500938/fast-cpp-csv-parser.zip)

**Comment by msharov** [comment]
Commit cb6124c661ed4aacfafe332b56ad19ad7648a823 adds operator!=(pointer) to smart pointers.
Commit 71b46b0757847bcd807390bb226091d3ccb20dde adds to_string(unsigned).

gcount is only applicable to text-based operations and so can not be implemented in istream, which in uSTL is binary.

I consider top level begin() and end() to be bad design through namespace pollution. Their omission is intentional. There is a VectorEnd macro to replace end(a) for arrays, and VectorRange(a) that generates the begin(a),end(a) equivalent.

**Comment by msharov** [comment]
After some consideration, I changed my mind about begin() and end(). Adding with commit aa3268ad55d51c0025bbed7923833975cd52f5ed.
