### ISSUE TITLE
Fail to compile on OSX

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#89]
Hello !
To be able to compile I needed to specify the "CC" and "CXX" environment variables to "clang" and "clang++" because if not the ./configure would use "gcc" and "g++" and will generate lot's of errors.

Looking at libstd++ implementations I could see that they have specific chrono code for OSX.
Also testing for " __clang_*__" version on OSX is misleading because the version that apple use is not the same as the official llvm/clang.  

To be able to compile ustl on OSX I need to exclude part of uchrono.h:
```
diff --git a/uchrono.h b/uchrono.h
index c87f3e2..4c82b5d 100644
--- a/uchrono.h
+++ b/uchrono.h
@@ -358,7 +358,7 @@ template <> struct time_point_text_write<system_clock::time_point> {
 
 //}}}-------------------------------------------------------------------
 //{{{ high_resolution_clock
-
+#ifdef HAVE_MONOTONIC_CLOCK
 struct high_resolution_clock {
     using duration	= ::ustl::chrono::duration<hrtime_t, nano>;
     using rep		= typename duration::rep;
@@ -375,8 +375,8 @@ public:
 
 //}}}-------------------------------------------------------------------
 //{{{ steady_clock
-
 // Monotonically increasing clock
+
 struct steady_clock : public high_resolution_clock {
     using duration	= nanoseconds;
     using rep		= typename duration::rep;
@@ -416,6 +416,7 @@ public:
 using system_clock_ms	= system_clock_hr<milliseconds>;
 using system_clock_us	= system_clock_hr<microseconds>;
 using system_clock_ns	= system_clock_hr<nanoseconds>;
+#endif
 
 //}}}-------------------------------------------------------------------
```
And also:
```
diff --git a/uttraits.h b/uttraits.h
index 0a4951d..24a07f2 100644
--- a/uttraits.h
+++ b/uttraits.h
@@ -370,7 +370,7 @@ struct __is_move_constructible {
 };
 template <typename T> struct is_move_constructible : public decltype(__is_move_constructible::test<T>(0)) {};
 
-#if __clang_major__ > 3 || (__clang_major__ == 3 && __clang_minor__ >= 9) || __GNUC__ >= 8
+#if ((__clang_major__ > 3 || (__clang_major__ == 3 && __clang_minor__ >= 9)) && !__APPLE__) || __GNUC__ >= 8
 template <typename T, typename U> struct is_assignable : public integral_constant<bool, __is_assignable(T,U)> {};
 #else
 struct __is_assignable {
``` 
Here is the manual modified Config.mk where I needed to change the version from 10.9 to 10.10 in my case:
```
################ Build options #######################################

NAME		:= ustl
MAJOR		:= 2
MINOR		:= 7

#DEBUG		:= 1
BUILD_SHARED	:= 1
BUILD_STATIC	:= 1
NOLIBSTDCPP	:= 1

################ Programs ############################################

CXX		:= clang++
LD		:= clang++
AR		:= ar
RANLIB		:= ranlib
INSTALL		:= install

INSTALLDATA	:= ${INSTALL} -p -m 644
INSTALLLIB	:= ${INSTALLDATA}
RMPATH		:= rmdir 

################ Destination #########################################

prefix		:= /Users/mingo/local
INCDIR		:= ${prefix}/include
LIBDIR		:= ${prefix}/lib
PKGCONFIGDIR	:= ${LIBDIR}/pkgconfig

################ Compiler options ####################################

WARNOPTS	:= -Wall -Wextra -Woverloaded-virtual -Wpointer-arith\
		-Wshadow -Wredundant-decls -Wcast-qual
TGTOPTS		:= -std=c++14 -I/Users/mingo/local/include
INLINEOPTS	:=

CXXFLAGS	:= ${WARNOPTS} ${TGTOPTS} -fPIC -ffunction-sections -fdata-sections
LDFLAGS		:= -L/Users/mingo/local/lib
LIBS		:=
ifdef DEBUG
    CXXFLAGS	+= -O0 -g
    LDFLAGS	+= -rdynamic
else
    CXXFLAGS	+= -Os -g0 -DNDEBUG=1 -fomit-frame-pointer ${INLINEOPTS}
    LDFLAGS	+= -mmacosx-version-min=10.10
endif
ifdef NOLIBSTDCPP
    LD		:= clang
    STAL_LIBS	:= -lc++abi
    LIBS	:= ${STAL_LIBS}
endif
BUILDDIR	:= /tmp/mingo/make/${NAME}
O		:= .o/

slib_lnk	= lib$1.dylib
slib_son	= lib$1.dylib.${MAJOR}
slib_tgt	= lib$1.dylib.${MAJOR}.${MINOR}
slib_flags	= -Wl,-single_module -compatibility_version 1 -current_version 1 -install_name $1 -Wl,-Y,1455 -dynamiclib -mmacosx-version-min=10.10
```

**Comment by msharov** [comment]
> To be able to compile I needed to specify the "CC" and "CXX"
> environment variables to "clang" and "clang++" because if not the 
> ./configure would use "gcc" and "g++" and will generate lot's of errors.

What kind of errors? If both gcc and clang are installed, uSTL prefers gcc because it always generates better code (~10-20% smaller). If gcc is not installed, configure should have correctly found clang and used it.

> #ifdef HAVE_MONOTONIC_CLOCK

And where is that coming from?

> testing for " clang*_" version on OSX is misleading because the 
> version that apple use is not the same as the official llvm/clang.

How is it misleading? What version does OSX think it has and what are the clang_ constants?

> LDFLAGS	+= -mmacosx-version-min=10.10

Where are you getting that number? Would uname be able to report it? Why does this flag matter, anyway?

I am not going to just drop random ifdefs in the code, especially not for a fringe platform like OSX. I need more specifics on how these differences can be detected by configure. Then workarounds can be placed into config.h.

**Comment by mingodad** [comment]
I'll look again when I have access to an OSX for more details and report it.
About clang macros see this http://sqlite.1065341.n5.nabble.com/Checking-gcc-clang-compiler-version-was-OS-X-Xcode-build-error-use-of-unknown-builtin-td94177.html
Cheers !

**Comment by mingodad** [comment]
Here you can see one way of how the OSX is done https://github.com/llvm-mirror/libcxx/blob/master/src/chrono.cpp
