### ISSUE TITLE
array class should be an aggregate type

### ISSUE THREAD

**Issue by ghita** [msharov/ustl#9]
That's at least how it's defined by the standard (c++ 11 where it was introduced first)
In this case constructors should be eliminated: 
like 
array (const array<T2,N>& v)		{ copy_n (v.begin(), N, _v); } 

Being an aggregate allows us initialization like  std::array<int. 2> x = {1, 2} -- which is not possible right now
Of course default 0 initialization would not happen with this change anymore, and array would behave in this regard as basic types

**Comment by msharov** [comment]
The constructors are already eliminated when compiling in C++11 mode. Before C++11, constructors are necessary to work around the lack of functionality required to implement it to the standard. The workaround is disabled with the HAVE_CPP11 macro, set to 1 in config.h when you are compiling in C++11 mode and have at least gcc 4.6 or clang 3.2.
