### ISSUE TITLE
What's the reason to not have a unordered_map in ustl ?

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#92]
USTL has already some years and why it doesn't have an unordered_map (hash table) ?
Is it because the memory model used by it make it hard/impossible to implement it ?
Someone did an intent https://github.com/antmicro/ustl_hashmap but abandoned without completion.
Hash tables have unique properties that makes then very useful and USTL that advocates for performance do not have one.

Cheers !

**Comment by mingodad** [comment]
I did some work on https://github.com/antmicro/ustl_hashmap and implemented the missing rehash method see attached.
Can it be used as starting point to add unordered_map to ustl ?
Cheers !

[ustl_hashmap.zip](https://github.com/msharov/ustl/files/2510445/ustl_hashmap.zip)

**Comment by msharov** [comment]
uSTL emphasizes size, not performance. In most cases hashmaps do not give significant performance advantages over binary searched maps, and by the time your dataset grows enough to warrant it, you should be using B-tree databases anyway. Adding yet another complex container that nobody should be using anyway would only introduce bloat, so no.
