### ISSUE TITLE
Consider remove all inline in `inline constexpr`

### ISSUE THREAD

**Issue by FirstLoveLife** [msharov/ustl#96]
constexpr has implied inline already.

**Comment by msharov** [comment]
uSTL is still supposed to work without any c++11 features, including constexpr.

**Comment by FirstLoveLife** [comment]
I know. So I mean `inline` in `inline constexpr`, not anywhere else.

**Comment by msharov** [comment]
Functions marked constexpr are not c++11-only; in c++98 mode constexpr is defined to nothing and they still compile. This includes functions such as min and max, which must be available when using any compiler.

**Comment by FirstLoveLife** [comment]
Ok, it makes sense. I didn't know constexpr is noop in compilers' c++98 mode
